## The number of worker processes, should be the same as your number
## of cores.
nworkers: 16

## Connection details of the backend server
target-ip: 127.0.0.1
#target-ip: 10.255.255.1
target-port: 8080

## If we can't connect to the server by this time, drop the connection
connect-timeout: 5000

## The proxy will accept connections on <listen-ip>:<listen-port>
## 0.0.0.0 means listen on every interface
listen-ip: 0.0.0.0
listen-port: 8443

## The certificate chain offered to clients
cacerts:
- cacert.pem
- intcert.pem
servcert: servcert.pem
servkey: servkey.pem
#servkeypass: test

## Alternatively, provide all certs (including server cert) in a single file:
# cert-chain: chain.pem
# servkey: servkey.pem
# servkeypass: test
## cacerts and servcert are mutually exclusive with cert-chain.

## If we implement mTLS:
# trusted-certs:
# - clientroot.pem
## In this example, only the root is provided. If your client doesn't send the
## chain certs, you will need to include the intermediate certs here.
## Also, if the client cert is self-signed or you don't have its chain, just
## put it in here.
