## Connection details of the backend server
target-ip: localhost
target-port: 80

## The proxy will accept connections on <listen-ip>:<listen-port>
## 0.0.0.0 means listen on every interface
listen-ip: 0.0.0.0
listen-port: 443

## The certificate chain offered to clients
cacerts:
- root.pem
- intermediate.pem
servcert: servcert.pem
servkey: servkey.pem
# servkeypass: test

## Alternatively, provide all certs (including server cert) in a single file:
# cert-chain: chain.pem
# servkey: servkey.pem
# servkeypass: test
## cacerts and servcert are mutually exclusive with cert-chain.

## If we implement mTLS:
# trusted-certs:
# - clientroot.pem
## In this example, only the root is provided. If your client doesn't send the
## chain certs, you will need to include the intermediate certs here.
## Also, if the client cert is self-signed or you don't have its chain, just
## put it in here.
